---
- name: Установить системнык зависимости через DNF
  ansible.builtin.package:
    name: python3-pip
    name: python3-requests
    state: present

- name: Обновить pip до последней версии
  ansible.builtin.pip:
    name: pip
    executable: pip3
    # executable: /usr/bin/pyhton3.9 -m pip3
    state: latest

- name: Установить docker SDK для Ansible
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
    # executable: /usr/bin/pyhton3.9 -m pip3
    executable: pip3
    state: present
